apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
    {{- include "transmission-openvpn.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transmission-openvpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "transmission-openvpn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "transmission-openvpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq .Values.provider.name "custom" }}
      initContainers:
      - name: copy-ro-custom-ovpn
        image: busybox
        command: ['sh', '-c', 'cp /ro/* /rw/']
        volumeMounts:
        - name: editable-custom-ovpn
          mountPath: "/rw"
        - name: custom-ovpn
          mountPath: /ro
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: {{- include "provider-config" $ | nindent 10 -}}
          {{- include "rpc-config" $ | nindent 10 }}
          - name: TZ
            value: {{ .Values.timezone | squote }}
          - name: PUID
            value: {{ .Values.user.uid | squote }}
          - name: PGID
            value: {{ .Values.user.gid | squote }}
          {{- if .Values.persistence.downloads.enabled }}
          - name: TRANSMISSION_DOWNLOAD_DIR
            value: '/downloads'
          {{- end }}
          {{- with .Values.extraEnv }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: dev-tun
            mountPath: "/dev/net/tun"
          {{- if eq .Values.provider.name "custom" }}
          - name: editable-custom-ovpn
            mountPath: "/etc/openvpn/custom/"
          {{- end }}
          {{- if .Values.persistence.config.enabled }}
          - name: transmission-data
            mountPath: /data
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.persistence.downloads.enabled }}
          - name: transmission-downloads
            mountPath: /downloads
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
      volumes:
      - name: dev-tun
        hostPath:
          path: "/dev/net/tun"
      {{- if eq .Values.provider.name "custom" }}
      - name: custom-ovpn
        secret:
          secretName: custom-ovpn
      - name: editable-custom-ovpn
        emptyDir: {}
      {{- end }}
      {{- if .Values.persistence.config.enabled }}
      - name: transmission-data
        persistentVolumeClaim:
          claimName: {{ include "transmission-openvpn.fullname" . | printf "config-%s" }}
      {{- end }}
      {{- if .Values.persistence.downloads.enabled }}
      - name: transmission-downloads
        persistentVolumeClaim:
          claimName: {{ include "transmission-openvpn.fullname" . | printf "downloads-%s" }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
