name: rook-ceph
image:
  repository: quay.io/ceph/ceph
  allowUnsupported: false
spec:
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  waitTimeoutForHealthyOSDInMinutes: 10
  upgradeOSDRequiresHealthyPGs: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNodes: false
    modules:
      - name: rook
        enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
    metricsDisabled: false
  network:
    connections:
      encryption:
        enabled: false
      compression:
        enabled: false
      requireMsgr2: false
  crashCollector:
    disable: false
  logCollector:
    enabled: true
    periodicity: daily
    maxLogSize: 500M
  cleanupPolicy:
    confirmation: '' # set to "yes-really-destroy-data" to delete
  storage:
    useAllNodes: false
    useAllDevices: false
  disruptionManagement:
   managePodBudgets: true
   osdMaintenanceTimeout: 30
   pgHealthCheckTimeout: 0
  csi:
    readAffinity:
      enabled: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    # Change pod liveness probe timing or threshold values. Works for all mon,mgr,osd daemons.
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    # Change pod startup probe timing or threshold values. Works for all mon,mgr,osd daemons.
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false

blockpool:
  name: main-block-pool
  failureDomain: host
  replicated:
    size: 1

storageclass:
  name: block


filesystem:
  name: filesystem
  preserveFilesystemOnDelete: false
  metadataServer:
    activeCount: 1
    activeStandby: false
  metadataPool:
    failureDomain: host
    replicated:
      size: 1
  dataPools:
    replicated:
      failureDomain: host
      replicated:
        size: 1
