apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ .Values.filesystem.name }}
spec:
  metadataPool:
    failureDomain: {{ .Values.filesystem.metadataPool.failureDomain }}
    replicated:
      size: {{ .Values.filesystem.metadataPool.replicated.size }}
  dataPools:
    {{- range $name, $values := .Values.filesystem.dataPools }}
    - name: {{ $name }}
      failureDomain: {{ $values.failureDomain }}
      replicated:
        size: {{ $values.replicated.size }}
    {{- end }}
  preserveFilesystemOnDelete: {{ .Values.filesystem.preserveFilesystemOnDelete }}
  metadataServer:
    activeCount: {{ .Values.filesystem.metadataServer.activeCount }}
    activeStandby: {{ .Values.filesystem.metadataServer.activeStandby }}
