apiVersion: mcr.mcr-operator.io/v1alpha1
kind: MinecraftProxy
metadata:
  name: velocity
spec:
  cluster:
    name: test-cluster
  host: test.palewhale.fr
  replicas: 1
  version: 3.4.0-SNAPSHOT
  service:
    loadBalancerIP: 172.17.69.2
    type: LoadBalancer
  
